### ISSUE TITLE
No option to edit roles

### ISSUE THREAD

**Issue by joksa97** [ferrumgate/secure.install#52]
Hello,

I have problem to edit roles on system and also to see what role is having what privileges (what are difference). Also is there a way to protect login of user portal with fail2ban or something other ?

**Comment by ferrumgate** [comment]
In system Roles are static, You cannot edit or delete, you can just assign.
There are 4 types of roles. I ordered them as I sorted as descending

1. Admin -> All
2. DevOps-> for only limited API call (Create user)
3. Reporter ->  Dashboard, Summary  for all users
4. User -> Does have nothing, only user related stuff

For login Protection,
Please enable Google Captcha, 
Also system has ratelimits, and authentication functions are so sensitive about limits. 
For future releases with are planning more about this concept. 

If you want to use fail2ban or something like that. you can follow logs with
ferrumgate --logs rest
ferrumgate --logs ssh
follow these logs you will see all trying ips there
if you create something, please share with us at
https://community.ferrumgate.com
