### ISSUE TITLE
Installation Problem / modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/6.5.11-8-pve

### ISSUE THREAD

**Issue by fsennj** [ferrumgate/secure.install#53]
trying to install on Proxmox LXC Debian 11 container:

root@ferrumgate:/home# ls
install.zip  secure.install
root@ferrumgate:/home# rm -rf install.zip 
root@ferrumgate:/home# cd secure.install/
root@ferrumgate:/home/secure.install# ls
README.md  docker.base.yaml  docker.gateway.yaml  install.sh  sh
root@ferrumgate:/home/secure.install# sh install.sh
[INFO]  check architecture
[INFO]  download install scripts from github
[INFO]  installing version 1.15.0
install.zip https://github.com/ferrumgate/secure.install/archive/refs/tags/v1.15.0.zip
Archive:  install.zip
134cc5946725a36c0c7a8782cdd3b5136d3ceb54
   creating: secure.install-1.15.0/
  inflating: secure.install-1.15.0/README.md  
  inflating: secure.install-1.15.0/docker.base.yaml  
  inflating: secure.install-1.15.0/docker.gateway.yaml  
  inflating: secure.install-1.15.0/install.sh  
   creating: secure.install-1.15.0/sh/
  inflating: secure.install-1.15.0/sh/common.sh  
  inflating: secure.install-1.15.0/sh/docker.sh  
  inflating: secure.install-1.15.0/sh/docker.swarm.sh  
  inflating: secure.install-1.15.0/sh/microk8s.sh  
  inflating: secure.install-1.15.0/sh/not.used.sh  
  inflating: secure.install-1.15.0/sh/prerequities.sh  
   creating: secure.install-1.15.0/sh/run/
  inflating: secure.install-1.15.0/sh/run/ferrumgate.sh  
  inflating: secure.install-1.15.0/sh/util.sh  
[INFO]  update system
Hit:1 http://deb.debian.org/debian bullseye InRelease
Get:2 http://security.debian.org bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Fetched 92.4 kB in 0s (315 kB/s)                                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[INFO]  install some needed packages
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
bmon is already the newest version (1:4.0-7).
ca-certificates is already the newest version (20210119).
conntrack is already the newest version (1:1.4.6-2).
curl is already the newest version (7.74.0-1.3+deb11u11).
gnupg is already the newest version (2.2.27-2+deb11u2).
htop is already the newest version (3.0.5-7).
ipcalc is already the newest version (0.42-2).
ipset is already the newest version (7.10-1).
ipvsadm is already the newest version (1:1.31-1+b1).
lsb-release is already the newest version (11.1.0).
net-tools is already the newest version (1.60+git20181103.0eebece-1).
ntp is already the newest version (1:4.2.8p15+dfsg-1).
sudo is already the newest version (1.9.5p2-3+deb11u1).
sysstat is already the newest version (12.5.2-2).
tcpdump is already the newest version (4.99.0-2+deb11u1).
unzip is already the newest version (6.0-26+deb11u1).
xxd is already the newest version (2:8.2.2434-3+deb11u1).
wireguard is already the newest version (1.0.20210223-1).
dnsutils is already the newest version (1:9.16.48-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[INFO]  load ipvs modules, and netfilter modules
br_netfilter
ip_vs
ip_vs_rr
ip_vs_wrr
ip_vs_sh
ip_vs_lc
ip_vs_dh
ip_vs_sed
ip_vs_nq
nf_conntrack
modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/6.5.11-8-pve
root@ferrumgate:/home/secure.install#

**Comment by ferrumgate** [comment]
Hi @fsennj , 
if 
**sudo modprobe br_netfilter**
is not working, it means your debian installation is not a standart distribution. some image providers are excluding some modules, etc...
please download from https://www.debian.org/releases/bullseye/debian-installer/  and use it.
