### ISSUE TITLE
gateway on another host

### ISSUE THREAD

**Issue by irraz** [ferrumgate/secure.install#59]
Hi I have deployed ferrumgate following the guide on a debian11 host. Now I want to deploy a gateway in a different cloud provider, but only the gateway to give connection in a virtual network different from where the master is located.

Is this possible?

**Comment by ferrumgate** [comment]
Yes you can connect to master from other cloud, please follow this document. only you need to use public IPv4 insted of private IPv4
https://ferrumgate.com/docs/architecture/how-to-make-a-cluster/#1-master-2-worker
